#
# If not stated otherwise in this file or this component's LICENSE file the
# following copyright and licenses apply:
#
# Copyright 2023 Liberty Global Technology Services BV
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "appstore-caching-charts.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "appstore-caching-charts.fullname" . }}
    helm.sh/chart: {{ include "appstore-caching-charts.chart" . }}
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: {{ include "appstore-caching-charts.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "appstore-caching-charts.fullname" . }}
    spec:
      enableServiceLinks: false
      initContainers:
      - args:
        - sed -i "s|https://petstore.swagger.io/v2/swagger.json|swagger.yaml|g" /usr/share/nginx/html/index.html; cp -R /usr/share/nginx/html/* /etc/nginx/swagger
        command:
          - /bin/sh
          - -c
        env:
          - name: STACK_NAME
            value: {{ include "appstore-caching-charts.fullname" . }}-{{ .Release.Namespace }}
          - name: HOST_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: NAMESPACE
            value: {{ .Release.Namespace }}
        name: {{ include "appstore-caching-charts.fullname" . }}-init
        imagePullPolicy: IfNotPresent
        image: {{ required "Missing `.Values.deployment.initContainer.image`" .Values.deployment.initContainer.image }}
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
            - mountPath: /etc/nginx/swagger
              name: swagger-generator
      containers:
      - name: {{ include "appstore-caching-charts.name" . }}
        image: {{ required "Missing `.Values.deployment.container.image`" .Values.deployment.container.image }}:{{ .Chart.AppVersion }}
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        volumeMounts:
          - mountPath: "/etc/nginx/swagger"
            name: swagger-generator
          - mountPath: "/data"
            name: bundle-generator-service-data
        resources:
          requests:
            memory: "512Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
        envFrom:
        - configMapRef:
            name: {{ include "appstore-caching-charts.fullname" . }}
        env:
        - name: STACK_NAME
          value: {{ include "appstore-caching-charts.fullname" . }}-{{ .Release.Namespace }}
        - name: HOST_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE
          value: {{ .Release.Namespace }}
      volumes:
        - name: bundle-generator-service-data
          persistentVolumeClaim:
            claimName: {{ required "Missing `.Values.pvc.bundleGenerator.claimName`" .Values.pvc.bundleGenerator.claimName }}
            readOnly: true
        - name: swagger-generator
          emptyDir:
            sizeLimit: 64Mi