#
# If not stated otherwise in this file or this component's LICENSE file the
# following copyright and licenses apply:
#
# Copyright 2023 Liberty Global Technology Services BV
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

apiVersion: v1
entries:
  appstore-caching-service:
  - apiVersion: v1
    appVersion: 0.6.0
    created: "2023-06-13T13:26:51.787011268Z"
    description: Appstore Caching Service
    digest: cdf2d1a04a729ac6eac37c63750db24a221d70ab0f25fd4906bb79e501fb47d4
    home: https://github.com/LibertyGlobal/appstore-caching-service
    kubeVersion: '>=1.12.0-0'
    name: appstore-caching-service
    sources:
    - https://github.com/LibertyGlobal/appstore-caching-service
    urls:
    - https://libertyglobal.github.io/appstore-caching-service/charts/appstore-caching-service-0.6.0.tgz
    version: 0.6.0
generated: "2023-06-13T13:26:51.785969459Z"
