name: Builds the project
on:
  workflow_call:
    inputs:
      java-version:
        description: "JDK Version"
        type: string
        required: true
      version:
        description: "Version to build"
        type: string
        required: true
      pushDockerImage:
        description: "Push docker image"
        default: false
        type: boolean
    secrets:
      REGISTRY_USERNAME:
        required: true
      REGISTRY_PASSWORD:
        required: true
env:
  DOCKER_REGISTRY: docker.io
  DOCKER_IMAGE_NAME: appstore-caching-service

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          ref: v${{ inputs.version }}
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.java-version }}
          distribution: 'temurin'
          cache: maven
      - name: Build
        run:
          mvn package -DskipTests -DskipJarUpload=true -DscmCommit=${{ github.sha }} -DscmBranch=${{ github.ref_name }} -Ddocker_registry.username=${{ secrets.REGISTRY_USERNAME }} -Ddocker_registry.domain=${{ env.DOCKER_REGISTRY }} -Ddocker.image=${{ env.DOCKER_IMAGE_NAME }}
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Push
        run:
          docker push --all-tags ${{ env.DOCKER_REGISTRY }}/${{ secrets.REGISTRY_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}