name: Sets version on project
on:
  workflow_call:
    inputs:
      java-version:
        description: "JDK Version"
        type: string
        required: true
      version:
        description: "Version to set"
        type: string
        required: true
      commit:
        description: "Commit"
        type: boolean
        default: false
      commit_message:
        description: "Commit message"
        type: string
      create_tag:
        description: "Create tag"
        type: boolean
        default: false
env:
  CI_COMMIT_AUTHOR: Dac-Cloud-Bot
  CI_COMMIT_AUTHOR_EMAIL: dac-cloud@libertyglobal.com
  CI_COMMIT_MESSAGE: "[CI] ${{ inputs.commit_message }}"

jobs:
  set-version:
    if: inputs.commit == false
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.java-version }}
          distribution: 'temurin'
          cache: maven
      - name: Set next release version
        run: mvn versions:set -DnewVersion=${{ inputs.version }} -DprocessAllModules
  set-version-tag-and-commit:
    if: inputs.commit && inputs.create_tag
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.java-version }}
          distribution: 'temurin'
          cache: maven
      - name: GIT commit and push all changed files
        run: |
          git pull
          mvn versions:set -DnewVersion=${{ inputs.version }} -DprocessAllModules
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "${{ env.CI_COMMIT_AUTHOR_EMAIL }}"
          git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"
          git tag -a v${{ inputs.version }} -m "Version ${{ inputs.version }}"
          git push --tags
  set-version-and-commit:
    if: inputs.commit && inputs.create_tag == false
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.java-version }}
          distribution: 'temurin'
          cache: maven
      - name: GIT commit and push all changed files
        run: |
          git pull
          mvn versions:set -DnewVersion=${{ inputs.version }} -DprocessAllModules
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "${{ env.CI_COMMIT_AUTHOR_EMAIL }}"
          git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push
